// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASed_UkqLXVtPdnNP2M8c09jk8GewsAvc',
    appId: '1:451885187634:web:070b8d4d4e7a98799a722b',
    messagingSenderId: '451885187634',
    projectId: 'grademate-88d05',
    authDomain: 'grademate-88d05.firebaseapp.com',
    storageBucket: 'grademate-88d05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkp649EPFoEQ57QNMWIibGadCFVYJAA0o',
    appId: '1:451885187634:android:9023c34eb13e1dde9a722b',
    messagingSenderId: '451885187634',
    projectId: 'grademate-88d05',
    storageBucket: 'grademate-88d05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QQz8AG86KaZX0jcx3hW2xSteA2bMY3Q',
    appId: '1:451885187634:ios:6514d1eda020c9539a722b',
    messagingSenderId: '451885187634',
    projectId: 'grademate-88d05',
    storageBucket: 'grademate-88d05.firebasestorage.app',
    iosBundleId: 'com.example.grademate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-QQz8AG86KaZX0jcx3hW2xSteA2bMY3Q',
    appId: '1:451885187634:ios:6514d1eda020c9539a722b',
    messagingSenderId: '451885187634',
    projectId: 'grademate-88d05',
    storageBucket: 'grademate-88d05.firebasestorage.app',
    iosBundleId: 'com.example.grademate',
  );
}
